name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      # - name: Setup Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20.x
      - name: Build & Deploy
        uses: appleboy/ssh-action@master
        # env:
        #   PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        #   HOSTNAME: ${{ secrets.SSH_HOST }}
        #   USER_NAME: ${{ secrets.USER_NAME }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.APP_DIR }} &&
            git checkout main &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin main &&
            npm i &&
            npm run build
